-- ==============================================================================
--  BFHitEffects Client Logic
-- ==============================================================================
--  Description: Reads configuration, registers the in‑game settings menu,
--  and synchronises player choices to the front‑end JavaScript in real time.
--  Namespace: all global functions exposed to JS are prefixed with
--  "BFHitEffects_" to avoid collisions!
-- ==============================================================================

local tagConfig = require("config")

--  Defensive programming: hoist sound counts to top‑level scope to prevent
--  crashes if they are read as nil inside event callbacks.
--  Players can change the Count values in config.lua – they are read here automatically.
local soundHeadshotCount = tonumber(tagConfig.SoundHeadshot.Count) or 2
local soundNormalCount   = tonumber(tagConfig.SoundNormal.Count) or 2
local soundSpecialCount  = tonumber(tagConfig.SoundSpecial.Count) or 2
local soundExplosiveCount= tonumber(tagConfig.SoundExplosive.Count) or 2

-- Read hit feedback config (players can adjust in config.lua)
local hitFeedbackConfig = tagConfig.HitFeedback or {}
local hfEnabled = hitFeedbackConfig.Enabled ~= false  -- default on
local hfSoundEnabled = hitFeedbackConfig.SoundEnabled ~= false

-- Read damage number config (players can adjust in config.lua)
local damageNumbersConfig = tagConfig.DamageNumbers or {}
local dnEnabled = damageNumbersConfig.Enabled ~= false

-- ============================================================================
-- 1. Register in‑game settings menu (players can tweak these directly in the game)
-- ============================================================================

local m_Enabled = SettingsManager:DeclareBool("BFHitEffects_Enabled", tagConfig.Enabled, {
    displayName = "[BFHitEffects] Enable kill effects", showInUi = true
})
local m_SoundEnabled = SettingsManager:DeclareBool("BFHitEffects_SoundEnabled", tagConfig.SoundEnabled, {
    displayName = "[BFHitEffects] Enable kill sounds", showInUi = true
})

--  Note: In Lua string.format, '%' is a special character. To display '%' in the UI,
--  you must write '%%'!
local m_TextGlobalScale = SettingsManager:DeclareNumber("BFHitEffects_TextScale", tagConfig.TextGlobalScale or 100, 10.0, 200.0, {
    displayName = "[BFHitEffects] Text global scale (%)", showInUi = true
})
local m_IconGlobalScale = SettingsManager:DeclareNumber("BFHitEffects_IconScale", tagConfig.IconGlobalScale or 100, 10.0, 200.0, {
    displayName = "[BFHitEffects] Icon global scale (%)", showInUi = true
})

-- 2. Dynamically register settings for each tag (auto‑generated by loop; no code changes needed when adding tags)
--    Players can fine‑tune each tag from the settings menu.
local settings = {}
for tag, cfg in pairs(tagConfig.Tags) do
    local name = cfg.Name or tag

    settings[tag .. "_UseImg"] = SettingsManager:DeclareBool("BFHitEffects_" .. tag .. "_UseImg", cfg.IsImg, {
        displayName = string.format("[BFHitEffects] [%s] Use image", name), showInUi = true
    })
    settings[tag .. "_Text"] = SettingsManager:DeclareString("BFHitEffects_" .. tag .. "_Text", cfg.Text or tag, 1, 20, {
        displayName = string.format("[BFHitEffects] [%s] Fallback text", name), showInUi = true
    })
    settings[tag .. "_Color"] = SettingsManager:DeclareString("BFHitEffects_" .. tag .. "_Color", cfg.Color or "#FFFFFF", 7, 9, {
        displayName = string.format("[BFHitEffects] [%s] Text color (Hex)", name), showInUi = true
    })
    settings[tag .. "_Shadow"] = SettingsManager:DeclareNumber("BFHitEffects_" .. tag .. "_Shadow", cfg.Shadow or 1, 0, 2, {
        displayName = string.format("[BFHitEffects] [%s] Text shadow (0=none/1=stroke/2=glow)", name), showInUi = true
    })
    settings[tag .. "_IconScale"] = SettingsManager:DeclareNumber("BFHitEffects_" .. tag .. "_IconScale", cfg.IconScale or 100, 10.0, 200.0, {
        displayName = string.format("[BFHitEffects] [%s] Icon individual scale (%)", name), showInUi = true
    })
end

-- ============================================================================
-- 3. Core: pack all configuration into a JSON string and send it to JS
--    (automatically synchronised when the player changes config or settings)
-- ============================================================================
local function SyncSettingsToJS()
    -- Build the tag configuration object
    local updateObj = "{"
    local first = true
    for tag, cfg in pairs(tagConfig.Tags) do
        if not first then updateObj = updateObj .. "," end
        first = false

        -- Defensive reads: provide defaults
        local isImg = settings[tag .. "_UseImg"].value
        local text = string.gsub(settings[tag .. "_Text"].value or "", '"', '\\"')
        local color = settings[tag .. "_Color"].value or "#FFFFFF"
        local shadowType = tonumber(settings[tag .. "_Shadow"].value) or 1
        local iconScale = (tonumber(settings[tag .. "_IconScale"].value) or 100) / 100.0
        local aspectRatio = cfg.AspectRatio or "original"

        updateObj = updateObj .. string.format(
            '%s:{isImg:%s,text:"%s",color:"%s",shadowType:%d,iconScale:%.2f,aspectRatio:"%s"}',
            tag, tostring(isImg), text, color, shadowType, iconScale, aspectRatio
        )
    end
    updateObj = updateObj .. "}"

    -- Pack sound configuration
    local soundObj = string.format(
        '{headshot:{folder:"%s",count:%d}, normal:{folder:"%s",count:%d}, special:{folder:"%s",count:%d}, explosive:{folder:"%s",count:%d}}',
        tagConfig.SoundHeadshot.Folder or "headshot", soundHeadshotCount,
        tagConfig.SoundNormal.Folder or "normal", soundNormalCount,
        tagConfig.SoundSpecial.Folder or "special", soundSpecialCount,
        tagConfig.SoundExplosive.Folder or "explosive", soundExplosiveCount
    )

    -- Pack hit feedback config (values from config.lua are passed through)
    local hfConfig = hitFeedbackConfig
    local hfObj = string.format([[
        {
            enabled: %s,
            soundEnabled: %s,
            normal: {color:"%s", size:%d, thickness:%d, alpha:%.2f},
            headshot: {color:"%s", size:%d, thickness:%d, alpha:%.2f},
            kill: {color:"%s", size:%d, thickness:%d, alpha:%.2f},
            headshotKill: {color:"%s", size:%d, thickness:%d, alpha:%.2f},
            specialScale: %.2f,
            specialThickness: %.2f,
            fadeInMs: %d,
            fadeOutMs: %d,
            sound: {folder:"%s", count:%d}
        }
    ]],
        tostring(hfEnabled),
        tostring(hfSoundEnabled),
        hfConfig.Normal.Color or "#FFFFFF",
        hfConfig.Normal.Size or 40,
        hfConfig.Normal.Thickness or 3,
        hfConfig.Normal.Alpha or 0.8,
        hfConfig.Headshot.Color or "#FFAA00",
        hfConfig.Headshot.Size or 40,
        hfConfig.Headshot.Thickness or 3,
        hfConfig.Headshot.Alpha or 0.8,
        hfConfig.Kill.Color or "#FF0000",
        hfConfig.Kill.Size or 40,
        hfConfig.Kill.Thickness or 3,
        hfConfig.Kill.Alpha or 0.8,
        hfConfig.HeadshotKill.Color or "#FF00FF",
        hfConfig.HeadshotKill.Size or 40,
        hfConfig.HeadshotKill.Thickness or 3,
        hfConfig.HeadshotKill.Alpha or 0.8,
        hfConfig.SpecialScale or 1.5,
        hfConfig.SpecialThickness or 2.0,
        hfConfig.FadeInMs or 100,
        hfConfig.FadeOutMs or 300,
        (hfConfig.Sound and hfConfig.Sound.Folder) or "hit",
        (hfConfig.Sound and hfConfig.Sound.Count) or 2
    )

    -- Pack damage numbers config (values from config.lua are passed through)
    local dnConfig = tagConfig.DamageNumbers or {}
    local dnObj = string.format([[
        {
            enabled: %s,
            headshot: {color:"%s", size:%d, alpha:%.2f},
            normal: {color:"%s", size:%d, alpha:%.2f},
            fadeInMs: %d,
            fadeOutMs: %d,
            lifetimeMs: %d,
            fontFamily: "%s"
        }
    ]],
        tostring(dnEnabled),
        (dnConfig.Headshot and dnConfig.Headshot.Color) or "#FF0000",
        (dnConfig.Headshot and dnConfig.Headshot.Size) or 28,
        (dnConfig.Headshot and dnConfig.Headshot.Alpha) or 1.0,
        (dnConfig.Normal and dnConfig.Normal.Color) or "#FFFFFF",
        (dnConfig.Normal and dnConfig.Normal.Size) or 24,
        (dnConfig.Normal and dnConfig.Normal.Alpha) or 1.0,
        dnConfig.FadeInMs or 50,
        dnConfig.FadeOutMs or 150,
        dnConfig.LifetimeMs or 250,
        (dnConfig.FontFamily or "Alibaba PuHuiTi"):gsub('"', '\\"')
    )

    -- Final combined JS call
    local jsCode = string.format([[
        if(typeof BFHitEffects_UpdateSettings === 'function') {
            BFHitEffects_UpdateSettings({
                enabled: %s,
                textGlobalScale: %f,
                iconGlobalScale: %f,
                tags: %s,
                sounds: %s,
                hitFeedback: %s,
                damageNumbers: %s
            });
        }
    ]],
        tostring(m_SoundEnabled.value),
        (tonumber(m_TextGlobalScale.value) or 100) / 100.0,
        (tonumber(m_IconGlobalScale.value) or 100) / 100.0,
        updateObj,
        soundObj,
        hfObj,
        dnObj
    )
    WebUI:ExecuteJS(jsCode)
end

-- Synchronise config to front‑end when the extension loads
Events:Subscribe('Extension:Loaded', function()
    WebUI:Init()
    SyncSettingsToJS()
end)

-- Re‑sync whenever the player changes any option in the in‑game settings menu
Events:Subscribe('SettingsManager:SettingsChanged', function()
    SyncSettingsToJS()
end)

-- ============================================================================
-- 4. Receive kill events from the server (no player modification needed)
-- ============================================================================
NetEvents:Subscribe('BFHitEffects_KillEvent', function(tagsStr)
    if not m_Enabled.value then return end
    local baseTag = string.match(tagsStr, "([^,]+)") or "NORMAL"
    local folderType, soundIndex = "normal", 1

    if baseTag == "HEADSHOT" then
        folderType = "headshot"; soundIndex = MathUtils:GetRandomInt(1, soundHeadshotCount)
    elseif baseTag == "EXPLOSIVE" or baseTag == "VEHICLE_DESTRUCTION" then
        folderType = "explosive"; soundIndex = MathUtils:GetRandomInt(1, soundExplosiveCount)
    elseif baseTag ~= "NORMAL" then
        folderType = "special"; soundIndex = MathUtils:GetRandomInt(1, soundSpecialCount)
    else
        soundIndex = MathUtils:GetRandomInt(1, soundNormalCount)
    end

    WebUI:ExecuteJS(string.format('if(typeof BFHitEffects_AddKill === "function") BFHitEffects_AddKill("%s", "%s", %d);', tagsStr, folderType, soundIndex))
end)

-- Receive the independent “vehicle destroyed” event from the server
NetEvents:Subscribe('BFHitEffects_VehicleDestroyed', function()
    if not m_Enabled.value then return end
    WebUI:ExecuteJS('if(typeof BFHitEffects_AddKill === "function") BFHitEffects_AddKill("VEHICLE_DESTRUCTION", "explosive", 1);')
end)

-- ============================================================================
-- 5. Remove the vanilla hit feedback (Hitindicator node in the HUD)
-- ============================================================================
Hooks:Install('UI:PushScreen', 100, function(hook, screen, graphPriority, parentGraph)
    local screenAsset = UIGraphAsset(screen)
    local screenName = screenAsset.name

    if screenName == 'UI/Flow/Screen/HudMPScreen' then
        local clone = screen:Clone(screen.instanceGuid)
        local screenClone = UIGraphAsset(clone)

        local removed = false
        for i = #screenClone.nodes, 1, -1 do
            local node = screenClone.nodes[i]
            if node and node.name == 'Hitindicator' then
                screenClone.nodes:erase(i)
                removed = true
            end
        end

        if removed then
            hook:Pass(screenClone, graphPriority, parentGraph)
            return
        end
    end

    hook:Pass(screen, graphPriority, parentGraph)
end)

-- ============================================================================
-- 6. Receive hit feedback and damage number events (triggered by server‑side Soldier:Damage)
-- ============================================================================
NetEvents:Subscribe('BFHitEffects_HitEvent', function(hitType)
    if not hfEnabled then return end
    WebUI:ExecuteJS(string.format('if(typeof BFHitEffects_ShowHitFeedback === "function") BFHitEffects_ShowHitFeedback("%s");', hitType))
end)

NetEvents:Subscribe('BFHitEffects_DamageEvent', function(damage, isHeadshot)
    if not dnEnabled then return end
    WebUI:ExecuteJS(string.format('if(typeof BFHitEffects_ShowDamage === "function") BFHitEffects_ShowDamage(%d, %s);', damage, tostring(isHeadshot)))
end)